import { products, buildImages } from '../data/catalogue.js';
export const byId=id=>products.find(p=>p.id===id);
export const total=ids=>ids.filter(Boolean).reduce((n,id)=>n+(byId(id)?.price.amount||0),0);
export const power=ids=>ids.filter(Boolean).reduce((n,id)=>n+(['cpu','gpu','fans'].includes(byId(id)?.category)?(byId(id).specs.power||8):0),55);
export const buildImageFor=ids=>buildImages[ids.buildStyle]||buildImages.balanced;
const of=(category,test=()=>true)=>products.filter(p=>p.category===category&&test(p));
const score=(part,use,direction,p)=>{const s=part.scores||{}, key=use==='Gaming'?'gaming':use==='AI workloads'?'ai':use==='Video editing'||use==='Streaming'?'creative':use==='Programming'?'creative':'value';let n=(s[key]||part.specs.tier||55)*1.2+(s.value||60)*.35; if(direction==='value')n+=(s.value||60)*.8-part.price.amount*.015;if(direction==='aesthetic')n+=(part.colour===p.colour?28:0)+(part.rgb&&p.rgb!=='No RGB'?18:0)+(s.aesthetic||0);if(direction==='performance')n+=(s[key]||part.specs.tier||50)*.65;if(!['cpu','gpu'].includes(part.category))n-=part.price.amount*.08;if(p.noise==='Very quiet')n+=(s.quiet||0);return n;};
const choose=(category,choices,use,direction,p,avoid=[])=>choices.filter(x=>!avoid.includes(x.id)).sort((a,b)=>score(b,use,direction,p)-score(a,use,direction,p)||a.price.amount-b.price.amount)[0]||choices[0]||products.filter(x=>x.category===category&&(category!=='gpu'||use!=='AI workloads'||x.specs.vram>=12)).sort((a,b)=>a.price.amount-b.price.amount)[0];
const targetShare={Gaming:{gpu:.42,cpu:.17,ram:.07,storage:.06},'AI workloads':{gpu:.45,cpu:.16,ram:.12,storage:.09},'Video editing':{gpu:.27,cpu:.25,ram:.14,storage:.12},Streaming:{gpu:.34,cpu:.22,ram:.1,storage:.09},Programming:{gpu:.18,cpu:.25,ram:.15,storage:.11},'School / work':{gpu:.12,cpu:.23,ram:.12,storage:.1}};
export function compatibility(ids){const parts=ids.filter(Boolean).map(byId),find=c=>parts.find(x=>x.category===c),cpu=find('cpu'),board=find('motherboard'),ram=find('ram'),gpu=find('gpu'),cooler=find('cooler'),c=find('case'),psu=find('psu'),storage=find('storage'),issues=[];if(cpu&&board&&cpu.specs.socket!==board.specs.socket)issues.push('Incompatible — CPU socket does not match motherboard.');if(ram&&board&&ram.specs.memory!==board.specs.memory)issues.push('Incompatible — memory generation does not match motherboard.');if(gpu&&c&&gpu.specs.length>c.specs.gpuClearance)issues.push('Incompatible — GPU exceeds case clearance.');if(cooler&&cpu&&!cooler.specs.sockets.includes(cpu.specs.socket))issues.push('Incompatible — cooler socket support is missing.');if(cooler&&c&&cooler.specs.height>c.specs.coolerClearance)issues.push('Incompatible — cooler exceeds case clearance.');if(board&&c&&!c.specs.formFactors.includes(board.specs.formFactor))issues.push('Incompatible — case does not support motherboard form factor.');if(storage&&board&&storage.specs.interface==='M.2'&&board.specs.m2<1)issues.push('Incompatible — motherboard has no available M.2 support.');if(psu&&psu.specs.wattage<power(ids)*1.3)issues.push('Potential issue — PSU needs more safety headroom.');return issues;}
export function recommendationProfile(p){const focus=p.balance<40?'performance-led':p.balance>60?'aesthetics-led':'balanced';const storage=p.storage>=1024?`${p.storage/1024}TB`:`${p.storage}GB`;return{intent:p.use==='Gaming'?`${p.resolution} gaming`:`${p.use} workloads`,focus,constraints:[`${storage} storage`,p.noise,p.size,p.connectivity,p.upgrade],summary:`${focus} ${p.use.toLowerCase()} PC at a £${p.budget} budget, finished in ${p.colour} with ${p.rgb.toLowerCase()}.`};}
export function makeBuild(p,direction='balanced'){const share=targetShare[p.use]||targetShare.Gaming, ceiling=p.budget*.98;const coreBudget=Math.max(500,p.budget-300);const gpuLimit=coreBudget*share.gpu*(direction==='performance'?1.18:direction==='value'?.9:1),cpuLimit=coreBudget*share.cpu*(direction==='performance'?1.12:1);const premiumGpuLimit=p.budget>=2500?Math.min(ceiling*.8,p.budget*.78):0,premiumCpuLimit=p.budget>=2500?Math.min(ceiling*.35,p.budget*.25):0;const gpu=choose('gpu',of('gpu',x=>x.price.amount<=Math.max(gpuLimit*1.22,premiumGpuLimit)&&!(p.use==='AI workloads'&&x.specs.vram<12)),p.use,direction,p);const cpu=choose('cpu',of('cpu',x=>x.price.amount<=Math.max(cpuLimit*1.35,premiumCpuLimit)),p.use,direction,p,[direction==='value'?'cpu-b':null]);const board=choose('motherboard',of('motherboard',x=>x.specs.socket===cpu.specs.socket&&(p.connectivity==='Not needed'||x.specs.wifi)),p.use,direction,p);const ramNeed=(p.use==='AI workloads'||p.use==='Video editing')&&p.budget>=1400?64:p.budget<900?16:32;const ram=choose('ram',of('ram',x=>x.specs.memory===board.specs.memory&&x.specs.capacity>=ramNeed),p.use,direction,p);const storage=choose('storage',of('storage',x=>x.specs.capacity>=p.storage),p.use,direction,p);const c=choose('case',of('case',x=>x.specs.formFactors.includes(board.specs.formFactor)&&x.specs.gpuClearance>=gpu.specs.length&&(p.size==='Small form factor'?x.specs.formFactors.includes('mATX'):true)),p.use,direction,p);const cooler=choose('cooler',of('cooler',x=>x.specs.sockets.includes(cpu.specs.socket)&&x.specs.height<=c.specs.coolerClearance),p.use,direction,p);const psu=choose('psu',of('psu',x=>x.specs.wattage>=gpu.specs.power+cpu.specs.power+180),p.use,direction,p);const fans=choose('fans',of('fans',x=>direction==='aesthetic'?x.rgb||x.colour===p.colour:true),p.use,direction,p);let ids=[cpu.id,cooler.id,board.id,ram.id,gpu.id,storage.id,psu.id,c.id,fans.id];const categoryOrder=['gpu','cpu','storage','ram'];while(total(ids)>ceiling){let changed=false;for(const category of categoryOrder){const current=byId(ids.find(id=>byId(id).category===category));const alternatives=of(category,x=>x.price.amount<current.price.amount&&(category!=='storage'||x.specs.capacity>=p.storage));if(alternatives.length){const next=choose(category,alternatives,p.use,direction,p);ids=ids.map(id=>id===current.id?next.id:id);changed=true;break;}}if(!changed)break;}ids.buildStyle=direction;return ids;}
export function explainBuild(p,ids){const gpu=byId(ids.find(id=>byId(id).category==='gpu')),cpu=byId(ids.find(id=>byId(id).category==='cpu')),storage=byId(ids.find(id=>byId(id).category==='storage'));const workload=p.use==='AI workloads'?'AI compute and VRAM':p.use==='Video editing'?'multicore CPU, RAM and fast storage':p.use==='Gaming'?`${p.resolution} gaming`:'your everyday workload';return[`For ${workload}, ${gpu.name} and ${cpu.name} were selected from the current compatible catalogue.`,`${storage.name} meets your ${p.storage>=1024?`${p.storage/1024}TB`:`${p.storage}GB`} minimum without treating storage as a free extra.`,p.balance>60?`Your ${p.colour} finish and ${p.rgb.toLowerCase()} preference influence the case, cooling and fan selection.`:'The performance/value direction keeps more of the budget on workload-critical hardware.'];}
